const artists = [
  {
    id: "michael-jackson",
    name: "Michael Jackson",
    country: "United States",
    continent: "North America",
    genre: "Pop, R&B, soul, funk, disco, New Jack Swing ,Hip-Hop, rock",
    city: "Gary",
    state: "Indiana",
    diedin: "Los Angeles, California",
    becameFamousIn: "Gary, Indiana",
    birthDate: "August 29, 1958",
    deathDate: "June 25, 2009",
    deathReason: "Acute propofol and benzodiazepine intoxication",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/31/Michael_Jackson_in_1988.jpg",
    gifUrl: "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3FrNWpmdWVvcHVtdTQwc244ZzA3emMwb2RwMzNrazV0djJvNWt6diZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/100ak1Sn7F3ius/giphy.gif",
   impact: "Jackson pioneered the modern music video as narrative art with 'Thriller,' 'Billie Jean,' and 'Bad,' and his moonwalk and choreography became a global template for pop performance. 'Thriller' remains the best-selling album of all time, and his fusion of pop, funk, and R&B reshaped how mainstream music sounded and looked for decades."

  },

  {
    id: "burna-boy",
    name: "Burna Boy",
    country: "Nigeria",
    continent: "Africa",
    genre: "Afrobeats, reggae, dancehall, pop",
    city: "Port Harcourt",
    state: "Rivers",
    currentCity: "Lagos",
    becameFamousIn: "Lagos, Nigeria",
    birthDate: "July 2, 1991",
    deathDate: null,
    imageUrl: "https://www.thisismetropolis.com/wp-content/uploads/2023/09/burna-boy-is-back-with-his-fifth-studio-album-%E2%80%98i-told-them%E2%80%A6.-coming-off-the-back-of-his-record-b.jpg",
    gifUrl: null,
  impact: "Burna Boy helped carry Afrobeats from a regional Nigerian sound to global mainstream radio and festival stages, winning a Grammy for 'Twice as Tall' and headlining stadiums like Madison Square Garden. His work opened commercial doors for a generation of African artists now touring internationally."

  },

  {
    id: "tupac-shakur",
    name: "Tupac Amaru Shakur",
    country: "United States",
    continent: "North America",
    genre: "West Coast Hip-hop, Gangsta rap, Political hip-hop",
    city: "New York City",
    state: "New York",
    livedIn: "California",
    birthDate: "June 16, 1971",
    diedin: "Las Vegas, Nevada",
    becameFamousIn: "Los Angeles, California",
    deathDate: " September 13, 1996",
    deathReason: "Drive-by shooting,Shot on September 6th, died 7 days later",
    imageUrl: "https://hips.hearstapps.com/hmg-prod/images/tupac_shakur_photo_by_steve_eichner_archive_photos_getty_83928439.jpg",
    gifUrl: "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNDF5MWtuNmNydjZrazljdndzdWM4d2FmNzJ0N3R0cnV2bXAxa2xrMCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/HFoE92EZ9w2NG/giphy.gif",
    impact: "Tupac fused raw storytelling about poverty, police violence, and Black life in America with poetic vulnerability, making him one of the most quoted and studied lyricists in hip-hop history. Albums like 'Me Against the World' and 'All Eyez on Me' cemented gangsta rap as a vehicle for political and social commentary, not just street narrative."

  },
  {
    id: "lil-kim",
    name: "Lil Kim",
    country: "United States",
    continent: "North America",
    genre: "East Coast Hip-hop",
    city: "New York City",
    state: "New York",
    currentCity: "New York City",
    currentState: "New York",
    becameFamousIn: "New York City",
    birthDate: "October 27, 1970",
    deathDate: null,
    imageUrl: "https://www.thelist.com/img/gallery/what-happened-to-lil-kim-upgrade/intro-1689877921.jpg",
    gifUrl: null,
    impact: "Lil Kim's explicit, unapologetic sexuality and fashion-forward image on 'Hard Core' (1996) broke ground for women rappers in a male-dominated genre, directly influencing artists like Nicki Minaj and Cardi B. She proved a female rapper could control her own image and command commercial success on her own terms."

  },
  {id: "missy-elliott",
    name: "Missy Elliott",
    country: "United States",
    continent: "North America",
    genre: "Hip-hop, R&B, progressive rap, neo soul",
    city: "Portsmouth",
    state: "Virginia",
    becameFamousIn: "Virginia Beach, Virginia",
    currentCity: "Miami",
    currentState: "Florida",
    birthDate: "July 1, 1971",
    deathDate: null,
    imageUrl: "https://hips.hearstapps.com/hmg-prod/images/missy_elliot_photo_by_the_gap_getty_images_entertainment_getty_2370945.jpg",
    gifUrl: null,
   impact: "Missy Elliott redefined what a hip-hop artist and producer could sound and look like, pairing futuristic production with surreal, boundary-pushing music videos ('The Rain,' 'Get Ur Freak On'). As one of the first women to produce and write hits for herself and other major artists, she expanded the role of women behind the boards in hip-hop."
  },
  
  {
    id: "jennifer-lopez",
    name: "Jennifer Lopez",
    country: "United States",
    continent: "North America",
    genre: "Pop, R&B, Latin,Hip-hop,Dance",
    city: "New York City",
    state: "New York",
    becameFamousIn: "New York City",
    currentCity: "Los Angeles",
    currentState: "California",
    birthDate: "July 24, 1969",
    deathDate: null,
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/2/29/Jennifer_Lopez_-_J.Lo.png?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
    gifUrl: null,
   impact: "Lopez became one of the first Latina entertainers to build a simultaneous, top-tier career in music, film, and fashion in the U.S., helping open mainstream doors for Latin artists. 'On the 6' and her early-2000s crossover success made her a template for multi-hyphenate stardom."

  },
  { id: "beyonce",
    name: "Beyoncé",
    country: "United States",
    continent: "North America",
    genre: "Pop,R&B,Hip-hop",
    city: "Houston",
    state: "Texas",
    becameFamousIn: "Houston, Texas",
    currentCity: "Los Angeles",
    currentState: "California",
    birthDate: "September 4, 1981",
    deathDate: null,
    imageUrl: "https://media.allure.com/photos/6706905910e85e21685330bf/16:9/w_2560%2Cc_limit/beyonce%2520marilyn%2520monroe%2520bob%2520hero.jpg",
    gifUrl: null,
    impact: "Beyoncé redefined the album as a visual and conceptual art form with surprise releases like 'Beyoncé' (2013) and 'Lemonade' (2016), the latter a landmark exploration of Black womanhood and Southern identity. She holds the record for most Grammy wins of any artist, and 'Renaissance' and 'Cowboy Carter' pushed her into house and country music, challenging genre gatekeeping along the way."

  },
  
  
  
  
  {id: "eminem",
    name: "Eminem",
    country: "United States",
    continent: "North America",
    genre: "Hip-hop",
    city: "St. Joseph",
    state: "Missouri",
    becameFamousIn: "Detroit, Michigan",
    currentCity: "Detroit",
    currentState: "Michigan",
    birthDate: "October 17, 1972",
    deathDate: null,
    imageUrl: "https://cdn-web-main.bibliocms.com/wp-content/uploads/sites/3/2022/09/36079964425_7b3042d5e1_k.jpg",
    gifUrl: null,
   impact: "Eminem became one of the best-selling hip-hop artists in history, using technically dense rhyme schemes and confessional, often controversial lyricism to bring rap to a massive white suburban audience. Albums like 'The Marshall Mathers LP' sparked ongoing debates about race, authenticity, and free expression in hip-hop."
  },
  {id: "madonna",
    name: "Madonna",
    country: "United States",
    continent: "North America",
    genre: "Pop,electronic,dance",
    city: "Bay City",
    state: "Michigan",
    becameFamousIn: "New York City",
    currentCity: "Los Angeles",
    currentState: "California",
    birthDate: "August 16, 1958",
    deathDate: null,
    imageUrl: "https://faroutmagazine.co.uk/static/uploads/1/2022/10/Madonna-on-her-biggest-regrets-1140x855.jpg",
    gifUrl: null,
  impact: "Madonna built the model for modern pop reinvention, changing sound, image, and persona with nearly every album while pushing boundaries around sexuality and religious imagery in mainstream culture. Her control over her own career and image influenced generations of pop stars who followed."}
,
  {id: "prince",
    name: "Prince",
    country: "United States",
    continent: "North America",
    genre: "Pop, funk, rock,R&B,Soul,minneapolis sound,neo-psychedelia",
    city: "New York City",
    state: "New York",
    becameFamousIn: "Minneapolis, Minnesota",
    diedin: "Minneapolis, Minnesota",
    birthDate: "September 23, 1958",
    deathDate: "April 21, 2016",
    deathReason:"died of an accidental overdose of fentanyl",
    imageUrl: "https://acclaimmag.com/wp-content/uploads/2014/06/Prince240114.jpg",
    gifUrl: "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmM5d2RuYWVhNnZ1eWhvaXR0dnl2cXd6ZnZldWIwemFlaTV4NnlzeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/nuOgFcCrQyOg8/giphy.gif",
    impact: "Prince blurred the lines between funk, rock, pop, and R&B while writing, producing, and playing nearly every instrument on his own records — a rare level of total creative control. His fight with his label over ownership of his masters and his name change to an unpronounceable symbol made him an early, influential voice for artists' rights."

  },
{id: "george-michael",
    name: "George Michael",
    country: "United Kingdom",
    continent: "Europe",
    genre: "Pop,Dance-pop,Post-disco,R&B",
    city: "East Finchley",
    state: "Greater London",
    becameFamousIn: "London, England",
    diedin: "London, England",
    birthDate: "June 25, 1963",
    deathDate: "December 25, 2016",
    deathReason:"died of natural causes related to heart and liver disease",
    imageUrl: "https://cdn.britannica.com/48/250948-050-8262760B/George-Michael-Wham-1987.jpg",
    gifUrl: "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExcDU1amNjdHZmMGVjb2xsc2dndjhpcmF6MjI4aG5wM2x5OTN5bmIybiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l1J9LAmCuvaOZ7tlu/giphy.gif",
    impact: "As part of Wham! and then as a solo artist with 'Faith,' George Michael became one of the defining voices of 1980s pop while writing and producing much of his own material, unusual for a pop star of that era. His public struggles with his record label over creative control and his eventual coming out made him an important figure in music industry and LGBTQ+ history."

  },
  {id: "whitney-houston",
    name: "Whitney Houston",
    country: "United States",
    continent: "North America",
    genre: "Pop, R&B, soul, gospel,dance,funk,new jack swing,",
    city: "Newark",
    state: "New Jersey",
    becameFamousIn: "Newark, New Jersey",
    diedin: "Los Angeles, California",
    birthDate: "August 9, 1963",
    deathDate: "February 11, 2012",
    deathReason: "died of accidental drowning in a bathtub, with heart disease and cocaine use as contributing factors",
    imageUrl: "https://cdn.artphotolimited.com/images/597605a07938f401374f0c92/1000x1000/whitney-houston-chanteuse.jpg ",
    gifUrl: "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExbHlqc200bmF2NXV6MmRkdDdpeDBpd284ZThjazYxcmE1Mjc4aDc3cCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/pc813za6IavBWpTxdG/giphy.gif",
    impact: "Whitney Houston's vocal power redefined the standard for pop and R&B singing, and 'I Will Always Love You' remains one of the best-selling singles by a woman in music history. She was also one of the first Black women to achieve mainstream crossover superstardom on MTV, opening doors that had previously been closed to Black artists on the network."

    },
    {id: "freddie-mercury",
    name: "Freddie Mercury",
    country: "United Kingdom",
    continent: "Europe",
    genre: "Rock,pop",
    city: "Stone Town",
    state: "zanzibar",
    becameFamousIn: "London, England",
    diedin: "London, England",
    birthDate: "September 5, 1946",
    deathDate: "November 24, 1991",
    deathReason: "Complications from AIDS",
    imageUrl: "https://www.etonline.com/sites/default/files/styles/default/public/images/2018-11/gettyimages-86098173.jpg",
    gifUrl: "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExaHUxcDR5dW40NmdhZGM5eTFuaWQyOTJnYmVocncwamVuYjI0c2pzbiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/nCOlMcPqfISxq/giphy.gif",
   impact: "As Queen's frontman, Mercury combined operatic vocal range with theatrical showmanship, helping create stadium rock as a genre with songs like 'Bohemian Rhapsody.' His 1991 death from AIDS-related complications, and his choice to confirm his diagnosis only a day before he died, significantly raised public awareness of the HIV/AIDS crisis."

  }, 
  {id: "kanye-west",
    name: "Kanye West",
    country: "United States",
    continent: "North America",
    genre: "Hip Hop, pop, electronic,soul, gospel, experimental",
    city: "Chicago",
    state: "Illinois",
    becameFamousIn: "Chicago, Illinois",
    currentCity: "Los Angeles",
    currentState: "California",
    birthDate: "June 8, 1977",
    deathDate: null,
    imageUrl: "https://media.zenfs.com/en/blavity_articles_483/5eea40c2cb107a5de7353962d796a640",
    gifUrl: null,
    impact: "Kanye West's early production work and albums like 'The College Dropout' and 'My Beautiful Dark Twisted Fantasy' pushed hip-hop toward soul sampling, emotional vulnerability, and maximalist production, reshaping the genre's sound repeatedly over two decades. His Yeezy fashion line also became one of the most commercially significant artist-driven brands in sneaker and streetwear culture."

  },
  {id: "r-kelly",
    name: "R. Kelly",
    country: "United States",
    continent: "North America",
    genre: "R&B, hip hop, soul, pop",
    city: "Chicago",
    state: "Illinois",
    becameFamousIn: "Chicago, Illinois",
    birthDate: "January 23, 1969",
    deathDate: null,
    isIncarcerated: true,
    statusText: "Currently incarcerated",
    imageUrl: "https://s.abcnews.com/images/Entertainment/r-kelly-gty-jt-180510_hpMain_16x9_1600.jpg",
    gifUrl: null,
    impact: "R. Kelly was a commercially dominant R&B writer and producer in the 1990s and 2000s, credited with hits for himself and other major artists. He was convicted in 2022 of racketeering and sex trafficking following decades of allegations of sexual abuse of minors, and his case became a central reference point in public reckonings with abuse in the music industry."

  },
  {id: "kendrick-lamar",
    name: "Kendrick Lamar",
    country: "United States",
    continent: "North America",
    genre: "West Coast Hip-hop, Gangsta rap, Progressive rap,conscious hip-hop, alternative rap",
    city: "Compton",
    state: "California",
    becameFamousIn: "Compton, California",
    currentCity:  "Los Angeles",
    currentState: "California",
    birthDate: "May 17, 1987",
    deathDate: null,
    imageUrl: "https://nadiaeugenejo.com/wp-content/uploads/2018/02/kendrick-lamar-e1520827809187.jpg",
    gifUrl: null,
   impact: "Kendrick Lamar's densely layered storytelling on albums like 'good kid, m.A.A.d city' and 'To Pimp a Butterfly' brought jazz, funk, and spoken word into mainstream hip-hop, and he became the first non-classical, non-jazz artist to win the Pulitzer Prize for Music (2018, for 'DAMN.'). His work is widely studied for its engagement with Black identity, mental health, and systemic racism."

  },
  {id: "drake",
    name: "Drake",
    country: "Canada",
    continent: "North America",
    genre: "Hip Hop, R&B, Pop,trap",
    city: "Toronto",
    state: "Ontario",
    becameFamousIn: "Toronto, Ontario",
    currentCity: "Houston",
    currentState: "Texas",
    birthDate: "October 24, 1986",
    deathDate: null,
    imageUrl: "https://pyxis.nymag.com/v1/imgs/c22/b8d/28e2f9cef6a368b08210b53260a94e0933-19-drake.2x.rsocial.w600.jpg",
    gifUrl: null,
    impact: "Drake helped popularize melodic, R&B-inflected rap and turned Toronto into a recognized hub in hip-hop, influencing the genre's sound throughout the 2010s. He holds numerous Billboard chart records for most entries and most number-one albums by a solo artist in the Hot 100 era."

  },
  {id: "rihanna",
    name: "Rihanna",
    country: "Barbados",
    continent: "North America",
    genre: "Pop,R&B",
    city: "Bridgetown",
    state: "Saint Michael Parish", 
    becameFamousIn: "New York City",
   currentCity: "Los Angeles",
   currentState: "California",
   birthDate: "February 20, 1988",
    deathDate: null,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST0mfU4jqdtbUO7jjFsz36RJ1vGlA4gmuHS96aSYEqu1NKebB42unwHR4&s=10",
    gifUrl: null,
    impact: "Rihanna became one of the best-selling music artists in history while also building Fenty Beauty into a groundbreaking cosmetics line known for an unusually wide shade range, credited with pushing the beauty industry toward broader inclusivity. Her willingness to shift genres — reggae, dance-pop, hip-hop — across her catalog made her one of pop's most commercially adaptable stars."

  },
  {id: "fantan-mojah",
    name: "Owen Lennox Moncrieffe",
    country: "Jamaica",
    continent: "North America",
    genre: "Reggae",
   city: "Elderslie", 
  state: "Saint Elizabeth Parish", 
  birthDate: "August 5, 1976",
  becameFamousIn: "Kingston, Jamaica",
  diedin: "Kingston, Jamaica",
  deathDate: "July 14, 2026",
  deathReason: " died from complications related to a prolonged heart condition",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRLonfsM1BwBRX7_ASY0aRxGQsSAKqnHAcFrBDcfEuyZik3sCpCSQ0Joq_jU3gp1OHtjxCHYq83GgcYq566wy3FUOvBxOZHBqKr0Uh04o&s=10",
    gifUrl: null,
   impact: "Fantan Mojah became a leading voice in the roots reggae revival of the 2000s, known for spiritually and socially conscious lyrics in the Rastafarian tradition, carrying forward the political and religious themes of earlier reggae greats to a new generation of Jamaican audiences."
  },
  {id: "bob-marley",
    name: "Robert Nesta Marley",
    country: "Jamaica",
    genre: "Reggae, ska, rocksteady,folk",
    city: "Nine Mile", 
  state: "Saint Ann Parish", 
  becameFamousIn: "Kingston, Jamaica",
  diedin: "Miami, Florida",
  birthDate: "February 6, 1945",
  deathDate: "May 11, 1981",
  deathReason: "Melanoma, a form of skin cancer",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Bob-Marley.jpg/250px-Bob-Marley.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExemJzODM1djgweTNlYWFpdGZtemlodzMybTF2OTN4NjhoaHBmMGlldCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/cexyXqMu6nw2s/giphy.gif",
   impact: "Bob Marley brought reggae to a global audience and turned it into a vehicle for Pan-African and anti-colonial politics, with songs like 'Get Up, Stand Up' and 'Redemption Song' becoming international anthems of resistance. He remains the most commercially and culturally significant reggae artist in history, and his influence extends across pop, hip-hop, and protest music worldwide."
  },
  {id: "shaggy",
    name: "Orville Richard Burrell",
    country: "Jamaica",
    continent: "North America",
    genre: "Reggae,dancehall, reggae fusion, hip hop",
    city: "Kingston",
    state: "Saint Andrew Parish",
    becameFamousIn: "Kingston, Jamaica",
    currentCity: "Miami",
    currentState: "Florida",
    birthDate: "October 25, 1968",
    deathDate: null,
    imageUrl: "https://www.looktothestars.org/photo/2291-shaggy/story_half_width.jpg",
    gifUrl: null,
    impact: "Shaggy brought dancehall and reggae-pop fusion to mainstream Western radio with hits like 'It Wasn't Me' and 'Boombastic,' becoming one of the best-selling reggae artists globally and helping pave the way for dancehall's continued presence in pop music."
  },
  {id: "marvin-gaye",
    name: "Marvin Gaye",
    country: "United States",
    continent: "North America",
    genre: "Soul, R&B, Funk, jazz",
    city: "Washington",
    state: "District of Columbia",
    becameFamousIn: "Washington, District of Columbia",
    birthDate: "April 2, 1937",
    diedin: "Los Angeles, California",
    deathDate: "August 1, 1984",
    deathReason: "Shot by his father during an argument",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThaQtWFfk1G0HQtQyHO4SDshzLVNJ2pdxaVbj678Hsr7FaNEDHBZU7k4k&s=10",
    gifUrl: "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2l1bDJlcXZocGFxazdxdGxnamJmajY3MHljbnFyY3JmdTZqOXZoaSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7bu5yRiuit1MN7q0/giphy.gif",
  impact: "Marvin Gaye's 'What's Going On' (1971) transformed soul music by directly addressing war, poverty, and police brutality in a concept album format, expanding what commercial Black music was allowed to say. His blend of social consciousness and sensual balladry ('Let's Get It On') made him one of the most influential figures in soul and R&B history."},
   {id: "bob-dylan",
    name: "Bob Dylan",
    country: "United States",
    continent: "North America",
    genre: "Folk, Rock",
    city: "New York",
    state: "New York",
    becameFamousIn: "New York, New York",
    birthDate: "May 24, 1941",
    deathDate: null,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Bob-Dylan.jpg/250px-Bob-Dylan.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "Reshaped songwriting itself by proving pop lyrics could carry literary weight. Blowin in the Wind and The Times They Are a-Changin' became civil rights and anti-war anthems; he later won the Nobel Prize in Literature (2016), the first songwriter to do so."
  },
  {id: "aretha-franklin",
    name: "Aretha Franklin",
    country: "United States",
    continent: "North America",
    genre: "Soul, R&B",
    city: "Memphis",
    state: "Tennessee",
    becameFamousIn: "Detroit, Michigan",
    birthDate: "September 25, 1942",
    deathDate: "August 16, 2018",
    deathReason: "Died of pancreatic cancer on August 16, 2018, at the age of 76",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Aretha_Franklin_1960.jpg/250px-Aretha_Franklin_1960.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "The definitive voice of soul music and a symbol of Black female empowerment; her cover of \"Respect\" became an anthem for both civil rights and feminism."
  },
  {id: "stevie-wonder",
    name: "Stevie Wonder",
    country: "United States",
    continent: "North America",
    genre: "Soul, R&B, Funk",
    city: "Detroit",
    state: "Michigan",
    becameFamousIn: "Detroit, Michigan",
    birthDate: "May 13, 1950",
    deathDate: null,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Stevie_Wonder_1973.jpg/250px-Stevie_Wonder_1973.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "A rare artist who was both a pop hitmaker and a serious sonic innovator, pioneering synthesizer use (Moog) in soul/funk and writing socially conscious work like \"Living for the City.\" Blind since infancy, he's also a major figure in disability visibility in music."
  },
  {id: "diana-ross",
    name: "Diana Ross",
    country: "United States",
    continent: "North America",
    genre: "Pop, Soul",
    city: "Detroit",
    state: "Michigan",
    becameFamousIn: "Detroit, Michigan",
    birthDate: "March 26, 1944",
    deathDate: null,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Diana_Ross_1970.jpg/250px-Diana_Ross_1970.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "As lead singer of The Supremes, Diana Ross helped make Motown a dominant commercial and cultural force, becoming one of the first Black female pop stars to achieve mainstream crossover superstardom. Her solo career further cemented her as a template for the multi-hyphenate star, spanning music, film, and fashion."
  },
  {id: "tina-turner",
    name: "Tina Turner",
    country: "United States",
    continent: "North America",
    genre: "Rock and roll,R&B ,rock, soul, pop",
    city: "Brownsville",
    state: "Tennessee",
    becameFamousIn: "St. Louis, Missouri",
    birthDate: "November 26, 1939",
    diedin: "Küsnacht, Switzerland",
    deathDate: "May 24, 2023",
    deathReason: "Died after a long illness, having spoken openly in her later years about the health conditions she was living with.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Tina_Turner_1980.jpg/250px-Tina_Turner_1980.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "Tina Turner's raw, powerhouse vocal style and explosive stage presence redefined what a woman fronting a rock act could look and sound like. Her 1980s solo comeback after decades of an abusive marriage to Ike Turner became a widely cited story of resilience, and she's often cited as an influence on generations of rock and pop performers."
  },
  {id: "ray-charles",
    name: "Ray Charles",
    country: "United States",
    continent: "North America",
    genre: "Soul, R&B, Jazz",
    city: "greenville",
    state: "Florida",
    becameFamousIn: "Seattle, Washington",
    birthDate: "September 23, 1930",
    diedin: "Beverly Hills, California",
    deathDate: "June 10, 2004",
    deathReason:"Died of liver disease, after a long and full career and life.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Ray_Charles_1950.jpg/250px-Ray_Charles_1950.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "Ray Charles pioneered what became known as soul music by fusing gospel's vocal intensity with R&B and blues, and later helped bring country music to Black audiences and vice versa with 'Modern Sounds in Country and Western Music.' Blind since childhood, he's also a landmark figure in disability representation in the arts.",
  },
  {id: "james-brown",
    name: "James Brown",
    country: "United States",
    continent: "North America",
    genre: "Soul, R&B, Funk",
    city: "Tampa",
    state: "Florida",
    becameFamousIn: "Macon, Georgia",
    birthDate: "May 3, 1933",
    diedin: "Atlanta, Georgia",
    deathDate: "December 25, 2006",
  
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/James_Brown_1970.jpg/250px-James_Brown_1970.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "Known as the 'Godfather of Soul,' James Brown's rhythm-forward approach to funk — emphasizing the downbeat over melody — became foundational to funk, disco, and hip-hop, and his catalog remains one of the most sampled in music history."
  },
  {id:"rick-james",
    name: "Rick James",
    country: "United States",
    continent: "North America",
    genre: "Funk, Soul",
    city: "Detroit",
    state: "Michigan",
    becameFamousIn: "los Angeles, California",
    birthDate: "August 12, 1953",
    deathDate: "November 10, 2003",
    diedin: "Los Angeles, California",
    deathReason: "Died of congestive heart failure, with pneumonia as a contributing factor, on Christmas Day.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Rick_James_1970.jpg/250px-Rick_James_1970.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "Rick James pioneered 'punk-funk,' blending funk, rock, and punk sensibilities; his hit 'Super Freak' became one of the most recognizable and heavily sampled tracks in hip-hop (notably by MC Hammer's 'U Can't Touch This')."
  },
  {id:"kes",
    name: "Kees Dieffenthaller",
    country: "Trinidad and Tobago",
    continent: "Central America",
    genre: " R&B, Pop, Rock, Soca, EDM,reggae",
    city: "Port of Spain",
    state: " Trinidad and Tobago",
    becameFamousIn: "Port of Spain, Trinidad and Tobago",
    birthDate: "March 12, 1980.",
    deathDate: null,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Kes_and_the_Band_1970.jpg/250px-Kes_and_the_Band_1970.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "Kes has been one of the leading modern ambassadors of soca music, helping transition the genre from a seasonal, Trinidad Carnival-dependent sound into a year-round international phenomenon with global festival crossover."
  },
  {id:"shabba-ranks",
    name: "Rexton Rawlston Fernando Gordon",
    country: "Jamaica",
    continent: "North America",
    genre: "Dancehall, Reggae",
    city: "Kingston",
    state: "Jamaica",
    becameFamousIn: "Kingston, Jamaica",
    birthDate: "October 15, 1968",
    deathDate: null,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Shabba_Ranks_1970.jpg/250px-Shabba_Ranks_1970.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "Shabba Ranks was the first dancehall artist to win a Grammy Award (Best Reggae Album, 1992), helping establish dancehall as a commercially viable genre on the international stage."
  },
{id:"elvis-presley",
    name: "Elvis Presley",
    country: "United States",
    continent: "North America",
    genre: "Rock and Roll, Pop",
    city: "Memphis",
    state: "Tennessee",
    becameFamousIn: "Memphis, Tennessee",
    birthDate: "January 12, 1935",
    deathDate: "August 16, 1977",
    diedin: "Memphis, Tennessee",
    deathReason:"Died of a heart attack, with prescription medication use a significant contributing factor in his declining health at the time.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Elvis_Presley_1970.jpg/250px-Elvis_Presley_1970.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "Elvis Presley became the most visible face of early rock and roll, bringing R&B and blues-rooted music to mainstream white American audiences in the 1950s — a legacy that's historically significant but also debated for the way it overshadowed the Black artists who originated the sound. His 1968 comeback special and Las Vegas residencies also helped define the modern concert spectacle."
  },
  {id:"adele",
    name: "Adele Laurie Blue Adkins",
    country: "United Kingdom",
    continent: "Europe",
    genre: "Pop, Soul",
    city: "London",
    state: "England",
    becameFamousIn: "London, England",
    birthDate: "May 27, 1988",
    deathDate: null,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Adele_1970.jpg/250px-Adele_1970.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "Adele revived big-voice, emotionally direct balladry in an era dominated by heavily produced pop. Her album '21' is among the best-selling albums of the 21st century and won Album of the Year at the Grammys."
  },
  {id:"bruno-mars",
    name: "Peter Gene Hernandez",
    country: "United States",
    continent: "North America",
    genre: "Pop, Funk",
    city: "Honolulu",
    state: "Hawaii",
    becameFamousIn: "los Angeles, California",
    birthDate: "October 5, 1987",
    deathDate: null,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Bruno_Mars_1970.jpg/250px-Bruno_Mars_1970.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "Bruno Mars built a career on genre-hopping retro authenticity — funk, soul, reggae, doo-wop — rather than chasing prevailing trends, and his collaborative Silk Sonic project with Anderson .Paak further cemented his reputation as a student and steward of classic soul and funk traditions."
  },
  {id:"lady-gaga",
    name: "Stefani Joanne Angelina Germanotta",
    country: "United States",
    continent: "North America",
    genre: "Pop",
    city: "New York City",
    state: "New York",
    becameFamousIn: "New York City, New York",
    birthDate: "March 28, 1986",
    deathDate: null,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Lady_Gaga_1970.jpg/250px-Lady_Gaga_1970.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "Lady Gaga pushed pop toward theatrical, boundary-pushing performance art, becoming a major LGBTQ+ ally and icon with songs like 'Born This Way.' Her pivot into film with 'A Star Is Born' (2018) also demonstrated a rare crossover between pop stardom and serious acting credibility."
  },
  {id:"gwen-stefani",
    name: "Gwen Renée Stefani",
    country: "United States",
    continent: "North America",
    genre: "Pop",
    city: "New York City",
    state: "New York",
    becameFamousIn: "anaheim, California",
    birthDate: "October 1, 1969",
    deathDate: null,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Gwen_Stefani_1970.jpg/250px-Gwen_Stefani_1970.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "As frontwoman of No Doubt, Gwen Stefani helped bring ska-punk into the mainstream in the 1990s; her solo career and distinctive fashion sense also made her an influential figure in 2000s pop aesthetics."
  },
  {id:"jojo",
    name: "Joanna Noëlle Levesque",
    country: "United States",
    continent: "North America",
    genre: "Pop",
    city: "New York City",
    state: "New York",
    becameFamousIn: "atlanta, Georgia",
    birthDate: "March 28, 1986",
    deathDate: null,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Jojo_1970.jpg/250px-Jojo_1970.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "JoJo became one of the youngest artists to have a #1 single at age 13 ('Leave (Get Out)'). She later became a prominent voice in the fight against exploitative record contracts after a years-long legal battle with her label prevented her from releasing new music, drawing industry attention to artist rights."
  },
  {id:"shakira",
    name: "Shakira Isabel Mebarak Ripoll",
    country: "Colombia",
    continent: "South America",
    genre: "Pop",
    city: "Bogotá",
    state: "Cundinamarca",
    becameFamousIn: "Bogotá, Colombia",
    birthDate: "February 12, 1977",
    deathDate: null,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Shakira_1970.jpg/250px-Shakira_1970.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "Shakira has been one of the most successful artists in bringing Latin pop to global mainstream audiences, blending Colombian and Middle Eastern musical influences into her sound. Hits like 'Hips Don't Lie' and her 2010 World Cup anthem 'Waka Waka' made her one of the best-selling Latin artists in history."
  },
  {id:"patti-labelle",
    name: "Patti LaBelle",
    country: "United States",
    continent: "North America",
    genre: "Pop",
    city: "New York City",
    state: "New York",
    becameFamousIn: "philadelphia, Pennsylvania",
    birthDate: "November 11, 1959",
    deathDate: null,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Patti_LaBelle_1970.jpg/250px-Patti_LaBelle_1970.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "Patti LaBelle, first with Labelle ('Lady Marmalade') and then as a solo artist, was a pioneering vocal powerhouse in soul and R&B whose influence is heard in generations of singers who followed. She's also built a notable second act as a food and lifestyle brand figure."
  },
  {id:"rick-ross",
    name: "William Leonard Roberts II",
    country: "United States",
    continent: "North America",
    genre: "Hip Hop",
    city: "New York City",
    state: "New York",
    becameFamousIn: "Miami, Florida",
    birthDate: "September 12, 1976",
    deathDate: null,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Rick_Ross_1970.jpg/250px-Rick_Ross_1970.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    gifUrl: null,
    impact: "Rick Ross is an American rapper and songwriter known for his deep, gravelly voice and introspective lyrics. He has been a prominent figure in the hip-hop scene since the early 2000s, releasing multiple successful albums and collaborating with various artists."
  }

];

export default artists;