const artist = [
  {
    "id": "michael-jackson",
    "name": "Michael Jackson",
    "country": "United States",
    "continent": "North America",
    "genre": "Pop, R&B, soul, funk, disco, New Jack Swing ,Hip-Hop, rock",
    "city": "Gary",
    "state": "Indiana",
    "diedin": "Los Angeles, California",
    "becameFamousIn": "1969",
    "becameFamousPlace": "Gary, Indiana, United States",
    "birthDate": "August 29, 1958",
    "deathDate": "June 25, 2009",
    "deathReason": "Acute propofol and benzodiazepine intoxication",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/3/31/Michael_Jackson_in_1988.jpg",
    "gifUrl": "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3FrNWpmdWVvcHVtdTQwc244ZzA3emMwb2RwMzNrazV0djJvNWt6diZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/100ak1Sn7F3ius/giphy.gif",
    "impact": "Jackson pioneered the modern music video as narrative art with 'Thriller,' 'Billie Jean,' and 'Bad,' and his moonwalk and choreography became a global template for pop performance. 'Thriller' remains the best-selling album of all time, and his fusion of pop, funk, and R&B reshaped how mainstream music sounded and looked for decades."
  },
  {
    "id": "burna-boy",
    "name": "Burna Boy",
    "country": "Nigeria",
    "continent": "Africa",
    "genre": "Afrobeats, reggae, dancehall, pop",
    "city": "Port Harcourt",
    "state": "Rivers",
    "currentCity": "Lagos",
    "becameFamousIn": "2012",
    "becameFamousPlace": "Lagos, Nigeria",
    "birthDate": "July 2, 1991",
    "deathDate": null,
    "imageUrl": "https://www.thisismetropolis.com/wp-content/uploads/2023/09/burna-boy-is-back-with-his-fifth-studio-album-%E2%80%98i-told-them%E2%80%A6.-coming-off-the-back-of-his-record-b.jpg",
    "gifUrl": null,
    "impact": "Burna Boy helped carry Afrobeats from a regional Nigerian sound to global mainstream radio and festival stages, winning a Grammy for 'Twice as Tall' and headlining stadiums like Madison Square Garden. His work opened commercial doors for a generation of African artists now touring internationally."
  },
  {
    "id": "tupac-shakur",
    "name": "Tupac Amaru Shakur",
    "country": "United States",
    "continent": "North America",
    "genre": "West Coast Hip-hop, Gangsta rap, Political hip-hop",
    "city": "New York City",
    "state": "New York",
    "livedIn": "California",
    "birthDate": "June 16, 1971",
    "diedin": "Las Vegas, Nevada",
    "becameFamousIn": "1991",
    "becameFamousPlace": "Los Angeles, California, United States",
    "deathDate": " September 13, 1996",
    "deathReason": "Drive-by shooting,Shot on September 6th, died 7 days later",
    "imageUrl": "https://hips.hearstapps.com/hmg-prod/images/tupac_shakur_photo_by_steve_eichner_archive_photos_getty_83928439.jpg",
    "gifUrl": "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNDF5MWtuNmNydjZrazljdndzdWM4d2FmNzJ0N3R0cnV2bXAxa2xrMCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/HFoE92EZ9w2NG/giphy.gif",
    "impact": "Tupac fused raw storytelling about poverty, police violence, and Black life in America with poetic vulnerability, making him one of the most quoted and studied lyricists in hip-hop history. Albums like 'Me Against the World' and 'All Eyez on Me' cemented gangsta rap as a vehicle for political and social commentary, not just street narrative."
  },
  {
    "id": "lil-kim",
    "name": "Lil Kim",
    "country": "United States",
    "continent": "North America",
    "genre": "East Coast Hip-hop",
    "city": "New York City",
    "state": "New York",
    "currentCity": "New York City",
    "currentState": "New York",
    "becameFamousIn": "1995",
    "becameFamousPlace": "New York City, New York, United States",
    "birthDate": "October 27, 1970",
    "deathDate": null,
    "imageUrl": "https://www.thelist.com/img/gallery/what-happened-to-lil-kim-upgrade/intro-1689877921.jpg",
    "gifUrl": null,
    "impact": "Lil Kim's explicit, unapologetic sexuality and fashion-forward image on 'Hard Core' (1996) broke ground for women rappers in a male-dominated genre, directly influencing artists like Nicki Minaj and Cardi B. She proved a female rapper could control her own image and command commercial success on her own terms."
  },
  {
    "id": "missy-elliott",
    "name": "Missy Elliott",
    "country": "United States",
    "continent": "North America",
    "genre": "Hip-hop, R&B, progressive rap, neo soul",
    "city": "Portsmouth",
    "state": "Virginia",
    "becameFamousIn": "1997",
    "becameFamousPlace": "Virginia Beach, Virginia, United States",
    "currentCity": "Miami",
    "currentState": "Florida",
    "birthDate": "July 1, 1971",
    "deathDate": null,
    "imageUrl": "https://hips.hearstapps.com/hmg-prod/images/missy_elliot_photo_by_the_gap_getty_images_entertainment_getty_2370945.jpg",
    "gifUrl": null,
    "impact": "Missy Elliott redefined what a hip-hop artist and producer could sound and look like, pairing futuristic production with surreal, boundary-pushing music videos ('The Rain,' 'Get Ur Freak On'). As one of the first women to produce and write hits for herself and other major artists, she expanded the role of women behind the boards in hip-hop."
  },
  {
    "id": "jennifer-lopez",
    "name": "Jennifer Lopez",
    "country": "United States",
    "continent": "North America",
    "genre": "Pop, R&B, Latin,Hip-hop,Dance",
    "city": "New York City",
    "state": "New York",
    "becameFamousIn": "1997",
    "becameFamousPlace": "New York City, New York, United States",
    "currentCity": "Los Angeles",
    "currentState": "California",
    "birthDate": "July 24, 1969",
    "deathDate": null,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/en/2/29/Jennifer_Lopez_-_J.Lo.png?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
    "gifUrl": null,
    "impact": "Lopez became one of the first Latina entertainers to build a simultaneous, top-tier career in music, film, and fashion in the U.S., helping open mainstream doors for Latin artists. 'On the 6' and her early-2000s crossover success made her a template for multi-hyphenate stardom."
  },
  {
    "id": "beyonce",
    "name": "Beyoncé",
    "country": "United States",
    "continent": "North America",
    "genre": "Pop,R&B,Hip-hop",
    "city": "Houston",
    "state": "Texas",
    "becameFamousIn": "1998",
    "becameFamousPlace": "Houston, Texas, United States",
    "currentCity": "Los Angeles",
    "currentState": "California",
    "birthDate": "September 4, 1981",
    "deathDate": null,
    "imageUrl": "https://media.allure.com/photos/6706905910e85e21685330bf/16:9/w_2560%2Cc_limit/beyonce%2520marilyn%2520monroe%2520bob%2520hero.jpg",
    "gifUrl": null,
    "impact": "Beyoncé redefined the album as a visual and conceptual art form with surprise releases like 'Beyoncé' (2013) and 'Lemonade' (2016), the latter a landmark exploration of Black womanhood and Southern identity. She holds the record for most Grammy wins of any artist, and 'Renaissance' and 'Cowboy Carter' pushed her into house and country music, challenging genre gatekeeping along the way."
  },
  {
    "id": "eminem",
    "name": "Eminem",
    "country": "United States",
    "continent": "North America",
    "genre": "Hip-hop",
    "city": "St. Joseph",
    "state": "Missouri",
    "becameFamousIn": "1999",
    "becameFamousPlace": "Detroit, Michigan, United States",
    "currentCity": "Detroit",
    "currentState": "Michigan",
    "birthDate": "October 17, 1972",
    "deathDate": null,
    "imageUrl": "https://cdn-web-main.bibliocms.com/wp-content/uploads/sites/3/2022/09/36079964425_7b3042d5e1_k.jpg",
    "gifUrl": null,
    "impact": "Eminem became one of the best-selling hip-hop artists in history, using technically dense rhyme schemes and confessional, often controversial lyricism to bring rap to a massive white suburban audience. Albums like 'The Marshall Mathers LP' sparked ongoing debates about race, authenticity, and free expression in hip-hop."
  },
  {
    "id": "madonna",
    "name": "Madonna",
    "country": "United States",
    "continent": "North America",
    "genre": "Pop,electronic,dance",
    "city": "Bay City",
    "state": "Michigan",
    "becameFamousIn": "1983",
    "becameFamousPlace": "New York City, New York, United States",
    "currentCity": "Los Angeles",
    "currentState": "California",
    "birthDate": "August 16, 1958",
    "deathDate": null,
    "imageUrl": "https://faroutmagazine.co.uk/static/uploads/1/2022/10/Madonna-on-her-biggest-regrets-1140x855.jpg",
    "gifUrl": null,
    "impact": "Madonna built the model for modern pop reinvention, changing sound, image, and persona with nearly every album while pushing boundaries around sexuality and religious imagery in mainstream culture. Her control over her own career and image influenced generations of pop stars who followed."
  },
  {
    "id": "prince",
    "name": "Prince",
    "country": "United States",
    "continent": "North America",
    "genre": "Pop, funk, rock,R&B,Soul,minneapolis sound,neo-psychedelia",
    "city": "Minneapolis",
    "state": "Minnesota",
    "becameFamousIn": "1979",
    "becameFamousPlace": "Minneapolis, Minnesota, United States",
    "diedin": "Minneapolis, Minnesota",
    "birthDate": "June 7, 1958",
    "deathDate": "April 21, 2016",
    "deathReason": "died of an accidental overdose of fentanyl",
    "imageUrl": "https://acclaimmag.com/wp-content/uploads/2014/06/Prince240114.jpg",
    "gifUrl": "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmM5d2RuYWVhNnZ1eWhvaXR0dnl2cXd6ZnZldWIwemFlaTV4NnlzeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/nuOgFcCrQyOg8/giphy.gif",
    "impact": "Prince blurred the lines between funk, rock, pop, and R&B while writing, producing, and playing nearly every instrument on his own records — a rare level of total creative control. His fight with his label over ownership of his masters and his name change to an unpronounceable symbol made him an early, influential voice for artists' rights."
  },
  {
    "id": "george-michael",
    "name": "George Michael",
    "country": "United Kingdom",
    "continent": "Europe",
    "genre": "Pop,Dance-pop,Post-disco,R&B",
    "city": "East Finchley",
    "state": "Greater London",
    "becameFamousIn": "1982",
    "becameFamousPlace": "London, England, United Kingdom",
    "diedin": "London, England",
    "birthDate": "June 25, 1963",
    "deathDate": "December 25, 2016",
    "deathReason": "died of natural causes related to heart and liver disease",
    "imageUrl": "https://cdn.britannica.com/48/250948-050-8262760B/George-Michael-Wham-1987.jpg",
    "gifUrl": "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExcDU1amNjdHZmMGVjb2xsc2dndjhpcmF6MjI4aG5wM3x5OTN5bmIybiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l1J9LAmCuvaOZ7tlu/giphy.gif",
    "impact": "As part of Wham! and then as a solo artist with 'Faith,' George Michael became one of the defining voices of 1980s pop while writing and producing much of his own material, unusual for a pop star of that era. His public struggles with his record label over creative control and his eventual coming out made him an important figure in music industry and LGBTQ+ history."
  },
  {
    "id": "whitney-houston",
    "name": "Whitney Houston",
    "country": "United States",
    "continent": "North America",
    "genre": "Pop, R&B, soul, gospel,dance,funk,new jack swing,",
    "city": "Newark",
    "state": "New Jersey",
    "becameFamousIn": "1985",
    "becameFamousPlace": "Newark, New Jersey, United States",
    "diedin": "Los Angeles, California",
    "birthDate": "August 9, 1963",
    "deathDate": "February 11, 2012",
    "deathReason": "died of accidental drowning in a bathtub, with heart disease and cocaine use as contributing factors",
    "imageUrl": "https://cdn.artphotolimited.com/images/597605a07938f401374f0c92/1000x1000/whitney-houston-chanteuse.jpg",
    "gifUrl": "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExbHlqc200bmF2NXV6MmRkdDdpeDBpd284ZThjazYxcmE1Mjc4aDc3cCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/pc813za6IavBWpTxdG/giphy.gif",
    "impact": "Whitney Houston's vocal power redefined the standard for pop and R&B singing, and 'I Will Always Love You' remains one of the best-selling singles by a woman in music history. She was also one of the first Black women to achieve mainstream crossover superstardom on MTV, opening doors that had previously been closed to Black artists on the network."
  },
  {
    "id": "freddie-mercury",
    "name": "Freddie Mercury",
    "country": "United Kingdom",
    "continent": "Europe",
    "genre": "Rock,pop",
    "city": "Stone Town",
    "state": "zanzibar",
    "becameFamousIn": "1974",
    "becameFamousPlace": "London, England, United Kingdom",
    "diedin": "London, England",
    "birthDate": "September 5, 1946",
    "deathDate": "November 24, 1991",
    "deathReason": "Complications from AIDS",
    "imageUrl": "https://www.etonline.com/sites/default/files/styles/default/public/images/2018-11/gettyimages-86098173.jpg",
    "gifUrl": "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExaHUxcDR5dW40NmdhZGM5eTFuaWQyOTJnYmVocncwamVuYjI0c2pzbiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/nCOlMcPqfISxq/giphy.gif",
    "impact": "As Queen's frontman, Mercury combined operatic vocal range with theatrical showmanship, helping create stadium rock as a genre with songs like 'Bohemian Rhapsody.' His 1991 death from AIDS-related complications, and his choice to confirm his diagnosis only a day before he died, significantly raised public awareness of the HIV/AIDS crisis."
  },
  {
    "id": "kanye-west",
    "name": "Kanye West",
    "country": "United States",
    "continent": "North America",
    "genre": "Hip Hop, pop, electronic,soul, gospel, experimental",
    "city": "Atlanta",
    "state": "Georgia",
    "becameFamousIn": "2004",
    "becameFamousPlace": "Chicago, Illinois, United States",
    "currentCity": "Los Angeles",
    "currentState": "California",
    "birthDate": "June 8, 1977",
    "deathDate": null,
    "imageUrl": "https://media.zenfs.com/en/blavity_articles_483/5eea40c2cb107a5de7353962d796a640",
    "gifUrl": null,
    "impact": "Kanye West's early production work and albums like 'The College Dropout' and 'My Beautiful Dark Twisted Fantasy' pushed hip-hop toward soul sampling, emotional vulnerability, and maximalist production, reshaping the genre's sound repeatedly over two decades. His Yeezy fashion line also became one of the most commercially significant artist-driven brands in sneaker and streetwear culture."
  },
  {
    "id": "r-kelly",
    "name": "R. Kelly",
    "country": "United States",
    "continent": "North America",
    "genre": "R&B, hip hop, soul, pop",
    "city": "Chicago",
    "state": "Illinois",
    "becameFamousIn": "1992",
    "becameFamousPlace": "Chicago, Illinois, United States",
    "birthDate": "January 23, 1969",
    "deathDate": null,
    "isIncarcerated": true,
    "statusText": "Currently incarcerated",
    "imageUrl": "https://s.abcnews.com/images/Entertainment/r-kelly-gty-jt-180510_hpMain_16x9_1600.jpg",
    "gifUrl": null,
    "impact": "R. Kelly was a commercially dominant R&B writer and producer in the 1990s and 2000s, credited with hits for himself and other major artists. He was convicted in 2022 of racketeering and sex trafficking following decades of allegations of sexual abuse of minors, and his case became a central reference point in public reckonings with abuse in the music industry."
  },
  {
    "id": "kendrick-lamar",
    "name": "Kendrick Lamar",
    "country": "United States",
    "continent": "North America",
    "genre": "West Coast Hip-hop, Gangsta rap, Progressive rap,conscious hip-hop, alternative rap",
    "city": "Compton",
    "state": "California",
    "becameFamousIn": "2012",
    "becameFamousPlace": "Compton, California, United States",
    "currentCity": "Los Angeles",
    "currentState": "California",
    "birthDate": "May 17, 1987",
    "deathDate": null,
    "imageUrl": "https://nadiaeugenejo.com/wp-content/uploads/2018/02/kendrick-lamar-e1520827809187.jpg",
    "gifUrl": null,
    "impact": "Kendrick Lamar's densely layered storytelling on albums like 'good kid, m.A.A.d city' and 'To Pimp a Butterfly' brought jazz, funk, and spoken word into mainstream hip-hop, and he became the first non-classical, non-jazz artist to win the Pulitzer Prize for Music (2018, for 'DAMN.'). His work is widely studied for its engagement with Black identity, mental health, and systemic racism."
  },
  {
    "id": "drake",
    "name": "Drake",
    "country": "Canada",
    "continent": "North America",
    "genre": "Hip Hop, R&B, Pop,trap",
    "city": "Toronto",
    "state": "Ontario",
    "becameFamousIn": "2009",
    "becameFamousPlace": "Toronto, Ontario, Canada",
    "currentCity": "Houston",
    "currentState": "Texas",
    "birthDate": "October 24, 1986",
    "deathDate": null,
    "imageUrl": "https://pyxis.nymag.com/v1/imgs/c22/b8d/28e2f9cef6a368b08210b53260a94e0933-19-drake.2x.rsocial.w600.jpg",
    "gifUrl": null,
    "impact": "Drake helped popularize melodic, R&B-inflected rap and turned Toronto into a recognized hub in hip-hop, influencing the genre's sound throughout the 2010s. He holds numerous Billboard chart records for most entries and most number-one albums by a solo artist in the Hot 100 era."
  },
  {
    "id": "rihanna",
    "name": "Rihanna",
    "country": "Barbados",
    "continent": "North America",
    "genre": "Pop,R&B",
    "city": "Bridgetown",
    "state": "Saint Michael Parish",
    "becameFamousIn": "2007",
    "becameFamousPlace": "New York City, New York, United States",
    "currentCity": "Los Angeles",
    "currentState": "California",
    "birthDate": "February 20, 1988",
    "deathDate": null,
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST0mfU4jqdtbUO7jjFsz36RJ1vGlA4gmuHS96aSYEqu1NKebB42unwHR4&s=10",
    "gifUrl": null,
    "impact": "Rihanna became one of the best-selling music artists in history while also building Fenty Beauty into a groundbreaking cosmetics line known for an unusually wide shade range, credited with pushing the beauty industry toward broader inclusivity. Her willingness to shift genres — reggae, dance-pop, hip-hop — across her catalog made her one of pop's most commercially adaptable stars."
  },
  {
    "id": "fantan-mojah",
    "name": "Owen Lennox Moncrieffe",
    "country": "Jamaica",
    "continent": "North America",
    "genre": "Reggae",
    "city": "Elderslie",
    "state": "Saint Elizabeth Parish",
    "becameFamousIn": "2005",
    "becameFamousPlace": "Kingston, Jamaica",
    "diedin": "Kingston, Jamaica",
    "birthDate": "August 5, 1976",
    "deathDate": "July 14, 2026",
    "deathReason": " died from complications related to a prolonged heart condition",
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRLonfsM1BwBRX7_ASY0aRxGQsSAKqnHAcFrBDcfEuyZik3sCpCSQ0Joq_jU3gp1OHtjxCHYq83GgcYq566wy3FUOvBxOZHBqKr0Uh04o&s=10",
    "gifUrl": null,
    "impact": "Fantan Mojah became a leading voice in the roots reggae revival of the 2000s, known for spiritually and socially conscious lyrics in the Rastafarian tradition, carrying forward the political and religious themes of earlier reggae greats to a new generation of Jamaican audiences."
  },
  {
    "id": "bob-marley",
    "name": "Robert Nesta Marley",
    "country": "Jamaica",
    "genre": "Reggae, ska, rocksteady,folk",
    "city": "Nine Mile",
    "state": "Saint Ann Parish",
    "becameFamousIn": "1973",
    "becameFamousPlace": "Kingston, Jamaica",
    "diedin": "Miami, Florida",
    "birthDate": "February 6, 1945",
    "deathDate": "May 11, 1981",
    "deathReason": "Melanoma, a form of skin cancer",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Bob-Marley.jpg/250px-Bob-Marley.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    "gifUrl": "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExemJzODM1djgweTNlYWFpdGZtemlodzMybTF2OTN4NjhoaHBmMGlldCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/cexyXqMu6nw2s/giphy.gif",
    "impact": "Bob Marley brought reggae to a global audience and turned it into a vehicle for Pan-African and anti-colonial politics, with songs like 'Get Up, Stand Up' and 'Redemption Song' becoming international anthems of resistance. He remains the most commercially and culturally significant reggae artist in history, and his influence extends across pop, hip-hop, and protest music worldwide."
  },
  {
    "id": "shaggy",
    "name": "Orville Richard Burrell",
    "country": "Jamaica",
    "continent": "North America",
    "genre": "Reggae,dancehall, reggae fusion, hip hop",
    "city": "Kingston",
    "state": "Saint Andrew Parish",
    "becameFamousIn": "1993",
    "becameFamousPlace": "Kingston, Jamaica",
    "currentCity": "Miami",
    "currentState": "Florida",
    "birthDate": "October 22, 1968",
    "deathDate": null,
    "imageUrl": "https://www.looktothestars.org/photo/2291-shaggy/story_half_width.jpg",
    "gifUrl": null,
    "impact": "Shaggy brought dancehall and reggae-pop fusion to mainstream Western radio with hits like 'It Wasn't Me' and 'Boombastic,' becoming one of the best-selling reggae artists globally and helping pave the way for dancehall's continued presence in pop music."
  },
  {
    "id": "marvin-gaye",
    "name": "Marvin Gaye",
    "country": "United States",
    "continent": "North America",
    "genre": "Soul, R&B, Funk, jazz",
    "city": "Washington",
    "state": "District of Columbia",
    "becameFamousIn": "1962",
    "becameFamousPlace": "Detroit, Michigan, United States",
    "birthDate": "April 2, 1937",
    "diedin": "Los Angeles, California",
    "deathDate": "August 1, 1984",
    "deathReason": "Shot by his father during an argument",
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThaQtWFfk1G0HQtQyHO4SDshzLVNJ2pdxaVbj678Hsr7FaNEDHBZU7k4k&s=10",
    "gifUrl": "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2l1bDJlcXZocGFxazdxdGxnamJmajY3MHljbnFyY3JmdTZqOXZoaSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7bu5yRiuit1MN7q0/giphy.gif",
    "impact": "Marvin Gaye's 'What's Going On' (1971) transformed soul music by directly addressing war, poverty, and police brutality in a concept album format, expanding what commercial Black music was allowed to say. His blend of social consciousness and sensual balladry ('Let's Get It On') made him one of the most influential figures in soul and R&B history."
  },
  {
    "id": "bob-dylan",
    "name": "Bob Dylan",
    "country": "United States",
    "continent": "North America",
    "genre": "Folk, Rock",
    "city": "New York",
    "state": "New York",
    "becameFamousIn": "1963",
    "becameFamousPlace": "New York City, New York, United States",
    "birthDate": "May 24, 1941",
    "deathDate": null,
    "imageUrl": "https://media.gq-magazine.co.uk/photos/5d13991f86dd7e0bf1553856/16:9/w_2560%2Cc_limit/Bob-Dylan-03-24May16_rex_b.jpg",
    "gifUrl": null,
    "impact": "Reshaped songwriting itself by proving pop lyrics could carry literary weight. Blowin in the Wind and The Times They Are a-Changin' became civil rights and anti-war anthems; he later won the Nobel Prize in Literature (2016), the first songwriter to do so."
  },
  {
    "id": "aretha-franklin",
    "name": "Aretha Franklin",
    "country": "United States",
    "continent": "North America",
    "genre": "Soul, R&B",
    "city": "Memphis",
    "state": "Tennessee",
    "becameFamousIn": "1967",
    "becameFamousPlace": "Detroit, Michigan, United States",
    "birthDate": "September 25, 1942",
    "deathDate": "August 16, 2018",
    "deathReason": "Died of pancreatic cancer on August 16, 2018, at the age of 76",
    "diedin": "Detroit, Michigan",
    "imageUrl": "https://www.pbs.org/wnet/americanmasters/files/2006/05/640px-Aretha_Franklin_1968-e1644530907648-640x360.jpg",
    "gifUrl": "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExMHNsMGt1ZXVrcTBvbGF4ZHJucTZieTB2eHBhNnk5cm10bG9zNGFhOSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3ohhwM7tGTyWI0ZfYA/giphy.gif",
    "impact": "The definitive voice of soul music and a symbol of Black female empowerment; her cover of \"Respect\" became an anthem for both civil rights and feminism."
  },
  {
    "id": "stevie-wonder",
    "name": "Stevie Wonder",
    "country": "United States",
    "continent": "North America",
    "genre": "Soul, R&B, Funk",
    "city": "Detroit",
    "state": "Michigan",
    "becameFamousIn": "1963",
    "becameFamousPlace": "Detroit, Michigan, United States",
    "birthDate": "May 13, 1950",
    "deathDate": null,
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8f/Stevie_Wonder_1994.jpg/250px-Stevie_Wonder_1994.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    "gifUrl": null,
    "impact": "A rare artist who was both a pop hitmaker and a serious sonic innovator, pioneering synthesizer use (Moog) in soul/funk and writing socially conscious work like \"Living for the City.\" Blind since infancy, he's also a major figure in disability visibility in music."
  },
  {
    "id": "diana-ross",
    "name": "Diana Ross",
    "country": "United States",
    "continent": "North America",
    "genre": "Pop, Soul",
    "city": "Detroit",
    "state": "Michigan",
    "becameFamousIn": "1964",
    "becameFamousPlace": "Detroit, Michigan, United States",
    "birthDate": "March 26, 1944",
    "deathDate": null,
    "imageUrl": "https://people.com/thmb/vpocoN_FYzQjNeFIlHbIzirvkck=/4000x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(749x0:751x2)/diana-ross-gallery19-1-bec119f0917a4c39803d33fbf4cca514.jpg",
    "gifUrl": null,
    "impact": "As lead singer of The Supremes, Diana Ross helped make Motown a dominant commercial and cultural force, becoming one of the first Black female pop stars to achieve mainstream crossover superstardom. Her solo career further cemented her as a template for the multi-hyphenate star, spanning music, film, and fashion."
  },
  {
    "id": "tina-turner",
    "name": "Tina Turner",
    "country": "United States",
    "continent": "North America",
    "genre": "Rock and roll,R&B ,rock, soul, pop",
    "city": "Brownsville",
    "state": "Tennessee",
    "becameFamousIn": "1960",
    "becameFamousPlace": "St. Louis, Missouri, United States",
    "birthDate": "November 26, 1939",
    "diedin": "Küsnacht, Switzerland",
    "deathDate": "May 24, 2023",
    "deathReason": "Died after a long illness, having spoken openly in her later years about the health conditions she was living with.",
    "imageUrl": "https://whyy.org/wp-content/uploads/2023/05/tina-turner-ap-2023-05-14-2.jpg",
    "gifUrl": "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExeGYwNDhhbm83OWNlMWRkd2xlOWhheGZ2MXk2NGtpbWJxeGUyZGczciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/8gfYkstn5t77dwSVof/giphy.gif",
    "impact": "Tina Turner's raw, powerhouse vocal style and explosive stage presence redefined what a woman fronting a rock act could look and sound like. Her 1980s solo comeback after decades of an abusive marriage to Ike Turner became a widely cited story of resilience, and she's often cited as an influence on generations of rock and pop performers."
  },
  {
    "id": "ray-charles",
    "name": "Ray Charles",
    "country": "United States",
    "continent": "North America",
    "genre": "Soul, R&B, Jazz, R&B, gospel, country,rock and roll",
    "city": "Albany",
    "state": "Georgia",
    "becameFamousIn": "1954",
    "becameFamousPlace": "Seattle, Washington, United States",
    "birthDate": "September 23, 1930",
    "diedin": "Beverly Hills, California",
    "deathDate": "June 10, 2004",
    "deathReason": "Died of liver disease, after a long and full career and life.",
    "imageUrl": "https://imagerenderer.com/images/images-profile-flow/400/images/artworkimages/mediumlarge/2/7-photo-of-ray-charles-david-redfern.jpg",
    "gifUrl": "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExdzFlM3FhdXRsc3FtYXVqdmY2bzZhNGFrczV0MmtrZWlkMXh0MTAxZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/rt0vFLR7GBxh6/giphy.gif",
    "impact": "Ray Charles pioneered what became known as soul music by fusing gospel's vocal intensity with R&B and blues, and later helped bring country music to Black audiences and vice versa with 'Modern Sounds in Country and Western Music.' Blind since childhood, he's also a landmark figure in disability representation in the arts."
  },
  {
    "id": "james-brown",
    "name": "James Brown",
    "country": "United States",
    "continent": "North America",
    "genre": "Soul, R&B, Funk",
    "city": "Tampa",
    "state": "Florida",
    "becameFamousIn": "1956",
    "becameFamousPlace": "Macon, Georgia, United States",
    "birthDate": "May 3, 1933",
    "diedin": "Atlanta, Georgia",
    "deathDate": "December 25, 2006",
    "imageUrl": "https://assets.vogue.com/photos/5891729d4fe1526113022460/master/w_2560%2Cc_limit/img-jamesbrown_104705700582.jpg",
    "gifUrl": "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2VodWR0MTAyMjFub3YycDR2aTEycGdsY3liOTd2ZTEyd3cxenNjcSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/mBBCCkyb6Yqjbo7ofs/giphy.gif",
    "impact": "Known as the 'Godfather of Soul,' James Brown's rhythm-forward approach to funk — emphasizing the downbeat over melody — became foundational to funk, disco, and hip-hop, and his catalog remains one of the most sampled in music history."
  },
  {
    "id": "rick-james",
    "name": "Rick James",
    "country": "United States",
    "continent": "North America",
    "genre": "Funk, Soul, R&B, rock, disco,doo-wap,post-disco",
    "city": "Detroit",
    "state": "Michigan",
    "becameFamousIn": "1978",
    "becameFamousPlace": "Los Angeles, California, United States",
    "birthDate": "August 12, 1953",
    "deathDate": "November 10, 2003",
    "diedin": "Los Angeles, California",
    "deathReason": "Died of congestive heart failure, with pneumonia as a contributing factor, on Christmas Day.",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Rick_James_in_Lifestyles_of_the_Rich_1984.JPG?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
    "gifUrl": "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExZTV5dzk5Mm9zbG5jbHRucm1sMzY3bmR4dGNrbnNkazB0dGk5bXJkdSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/56Fovu8pSSSYg/giphy.gif",
    "impact": "Rick James pioneered 'punk-funk,' blending funk, rock, and punk sensibilities; his hit 'Super Freak' became one of the most recognizable and heavily sampled tracks in hip-hop (notably by MC Hammer's 'U Can't Touch This')."
  },
  {
    "id": "kes",
    "name": "Kees Dieffenthaller",
    "country": "Trinidad and Tobago",
    "continent": "North America",
    "genre": " R&B, Pop, Rock, Soca, EDM,reggae",
    "city": "Port of Spain",
    "state": " Trinidad and Tobago",
    "becameFamousIn": "2011",
    "becameFamousPlace": "Port of Spain, Trinidad and Tobago",
    "birthDate": "March 12, 1980.",
    "deathDate": null,
    "imageUrl": "https://socanews.com/wp-content/uploads/2020/08/Kes-The-Band-group-jump.jpg",
    "gifUrl": null,
    "impact": "Kes has been one of the leading modern ambassadors of soca music, helping transition the genre from a seasonal, Trinidad Carnival-dependent sound into a year-round international phenomenon with global festival crossover."
  },
  {
    "id": "shabba-ranks",
    "name": "Rexton Rawlston Fernando Gordon",
    "country": "Jamaica",
    "continent": "North America",
    "genre": "Dancehall, Reggae, hip hop",
    "city": "Kingston",
    "state": "Jamaica",
    "becameFamousIn": "1991",
    "becameFamousPlace": "Kingston, Jamaica",
    "birthDate": "October 15, 1968",
    "deathDate": null,
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdSmFX2TYh3k9PU6TjcpAj0m35cALTOS7pYAafAcSFTcC3sco8ETo31_C_&s=10",
    "gifUrl": null,
    "impact": "Shabba Ranks was the first dancehall artist to win a Grammy Award (Best Reggae Album, 1992), helping establish dancehall as a commercially viable genre on the international stage."
  },
  {
    "id": "elvis-presley",
    "name": "Elvis Presley",
    "country": "United States",
    "continent": "North America",
    "genre": "Rock and Roll, Pop, rockabilly, gospel, rythm and blues, country,blues,soul",
    "city": "Memphis",
    "state": "Tennessee",
    "becameFamousIn": "1956",
    "becameFamousPlace": "Memphis, Tennessee, United States",
    "birthDate": "January 12, 1935",
    "deathDate": "August 16, 1977",
    "diedin": "Memphis, Tennessee",
    "deathReason": "Died of a heart attack, with prescription medication use a significant contributing factor in his declining health at the time.",
    "imageUrl": "https://hips.hearstapps.com/hmg-prod/images/gettyimages-138463874-678aa89c3e2e8.jpg?crop=1.00xw:0.709xh;0,0.110xh",
    "gifUrl": "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExb3R5MjFzb2xpeW90MXJobGN1NWpzdDFpbGRodDNyZXQyZ3hoZTVhciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xmXUarKqywPhS/giphy.gif",
    "impact": "Elvis Presley became the most visible face of early rock and roll, bringing R&B and blues-rooted music to mainstream white American audiences in the 1950s — a legacy that's historically significant but also debated for the way it overshadowed the Black artists who originated the sound. His 1968 comeback special and Las Vegas residencies also helped define the modern concert spectacle."
  },
  {
    "id": "adele",
    "name": "Adele Laurie Blue Adkins",
    "country": "United Kingdom",
    "continent": "Europe",
    "genre": "Pop, Soul",
    "city": "London",
    "state": "England",
    "becameFamousIn": "2008",
    "becameFamousPlace": "London, England, United Kingdom",
    "birthDate": "May 27, 1988",
    "deathDate": null,
    "imageUrl": "https://www.billboard.com/wp-content/uploads/media/Adele-2015-Alasdair-McLellan-billboard-650.jpg?w=650",
    "gifUrl": null,
    "impact": "Adele revived big-voice, emotionally direct balladry in an era dominated by heavily produced pop. Her album '21' is among the best-selling albums of the 21st century and won Album of the Year at the Grammys."
  },
  {
    "id": "bruno-mars",
    "name": "Peter Gene Hernandez",
    "country": "United States",
    "continent": "North America",
    "genre": "Pop, Funk, R&B, soul",
    "city": "Honolulu",
    "state": "Hawaii",
    "becameFamousIn": "2010",
    "becameFamousPlace": "Los Angeles, California, United States",
    "birthDate": "October 8, 1985",
    "deathDate": null,
    "imageUrl": "https://www.billboard.com/wp-content/uploads/media/Bruno-Mars-press-photo-Credit-Kai-Z-Feng-2016-012a-billboard-1548.jpg",
    "gifUrl": null,
    "impact": "Bruno Mars built a career on genre-hopping retro authenticity — funk, soul, reggae, doo-wop — rather than chasing prevailing trends, and his collaborative Silk Sonic project with Anderson .Paak further cemented his reputation as a student and steward of classic soul and funk traditions."
  },
  {
    "id": "lady-gaga",
    "name": "Stefani Joanne Angelina Germanotta",
    "country": "United States",
    "continent": "North America",
    "genre": "Pop, dance, electronic, jazz",
    "city": "New York City",
    "state": "New York",
    "becameFamousIn": "2008",
    "becameFamousPlace": "New York City, New York, United States",
    "birthDate": "March 28, 1986",
    "deathDate": null,
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQawye96QVhP85q7A1kYyOyIJ5MkPsi2L9y_yGbsdUUVyB8KNFLOPonB_Y&s=10",
    "gifUrl": null,
    "impact": "Lady Gaga pushed pop toward theatrical, boundary-pushing performance art, becoming a major LGBTQ+ ally and icon with songs like 'Born This Way.' Her pivot into film with 'A Star Is Born' (2018) also demonstrated a rare crossover between pop stardom and serious acting credibility."
  },
  {
    "id": "gwen-stefani",
    "name": "Gwen Renée Stefani",
    "country": "United States",
    "continent": "North America",
    "genre": "Pop, pop rock, ska punk, electro",
    "city": "Fullerton",
    "state": "California",
    "becameFamousIn": "1995",
    "becameFamousPlace": "Anaheim, California, United States",
    "birthDate": "October 3, 1969",
    "deathDate": null,
    "imageUrl": "https://hips.hearstapps.com/hmg-prod/images/gettyimages-2227909-1607353889.jpg?crop=1.00xw:0.627xh;0,0.0680xh&resize=640:*",
    "gifUrl": null,
    "impact": "As frontwoman of No Doubt, Gwen Stefani helped bring ska-punk into the mainstream in the 1990s; her solo career and distinctive fashion sense also made her an influential figure in 2000s pop aesthetics."
  },
  {
    "id": "jojo",
    "name": "Joanna Noëlle Levesque",
    "country": "United States",
    "continent": "North America",
    "genre": "R&B, pop, hip hop, soul",
    "city": "Brattleboro",
    "state": "Vermont",
    "becameFamousIn": "2004",
    "becameFamousPlace": "Foxborough, Massachusetts, United States",
    "birthDate": "December 20, 1990",
    "deathDate": null,
    "imageUrl": "https://i.redd.it/6lxfrkahor4a1.jpg",
    "gifUrl": null,
    "impact": "JoJo became one of the youngest artists to have a #1 single at age 13 ('Leave (Get Out)'). She later became a prominent voice in the fight against exploitative record contracts after a years-long legal battle with her label prevented her from releasing new music, drawing industry attention to artist rights."
  },
  {
    "id": "shakira",
    "name": "Shakira Isabel Mebarak Ripoll",
    "country": "Colombia",
    "continent": "South America",
    "genre": "Latin, pop, rock, dance",
    "city": "Barranquilla",
    "state": "Atlántico",
    "becameFamousIn": "1995",
    "becameFamousPlace": "Barranquilla, Colombia",
    "birthDate": "February 2, 1977",
    "deathDate": null,
    "imageUrl": "https://images.bild.de/6a744f4a37343a2e069f9892/e2077eae02a5b9341f47b89b89db7593,9a25c8d2?w=654",
    "gifUrl": null,
    "impact": "Shakira has been one of the most successful artists in bringing Latin pop to global mainstream audiences, blending Colombian and Middle Eastern musical influences into her sound. Hits like 'Hips Don't Lie' and her 2010 World Cup anthem 'Waka Waka' made her one of the best-selling Latin artists in history."
  },
  {
    "id": "patti-labelle",
    "name": "Patricia Louise Holte",
    "country": "United States",
    "continent": "North America",
    "genre": "R&B, soul, pop, dance",
    "city": "Philadelphia",
    "state": "Pennsylvania",
    "becameFamousIn": "1962",
    "becameFamousPlace": "Philadelphia, Pennsylvania, United States",
    "birthDate": "May 24, 1944",
    "deathDate": null,
    "imageUrl": "https://hips.hearstapps.com/hmg-prod/images/gettyimages-877936760.jpg",
    "gifUrl": null,
    "impact": "Patti LaBelle, first with Labelle ('Lady Marmalade') and then as a solo artist, was a pioneering vocal powerhouse in soul and R&B whose influence is heard in generations of singers who followed. She's also built a notable second act as a food and lifestyle brand figure."
  },
  {
    "id": "rick-ross",
    "name": "William Leonard Roberts II",
    "country": "United States",
    "continent": "North America",
    "genre": "Southern hip hop, gangsta rap",
    "city": "Clarksdale",
    "state": "Mississippi",
    "becameFamousIn": "2006",
    "becameFamousPlace": "Miami, Florida, United States",
    "birthDate": "January 28, 1976",
    "deathDate": null,
    "imageUrl": "https://d23sy9fe9womrt.cloudfront.net/1/53201_lg.jpg",
    "gifUrl": null,
    "impact": "Rick Ross built Maybach Music Group into a dominant hip-hop imprint, introducing artists like Meek Mill and Wale while defining 2010s luxury gangsta rap through expansive, cinematic production and his signature deep baritone delivery."
  },
  {
    "id": "emeli-sande",
    "name": "Emeli Sandé",
    "country": "United Kingdom",
    "continent": "Europe",
    "genre": "R&B, Soul, gospel",
    "city": "Sunderland",
    "state": "Tyne and Wear",
    "becameFamousIn": "2011",
    "becameFamousPlace": "London, United Kingdom",
    "birthDate": "March 10, 1987",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/52/Emeli_Sande_V_Festival_2012_%287830348954%29.jpg/330px-Emeli_Sande_V_Festival_2012_%287830348954%29.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    "gifUrl": null,
    "impact": "Revolutionized early 2010s British soul and pop with her powerhouse vocal delivery and emotive songwriting, earning massive mainstream commercial success and becoming a defining voice for landmark British cultural events including the 2012 London Olympics."
  },
  {
    "id": "solange",
    "name": "Solange Knowles",
    "country": "United States",
    "continent": "North America",
    "genre": " R&B",
    "city": "Houston",
    "state": "Texas",
    "becameFamousIn": "2002",
    "becameFamousPlace": "Houston, Texas, United States",
    "birthDate": "June 24, 1986",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://cdn.abcotvs.com/dip/images/398224_111614-ap-solange.jpg",
    "gifUrl": null,
    "impact": "Redefined modern alternative R&B and contemporary art performance through critically acclaimed album projects like 'A Seat at the Table', serving as a vital sonic and visual voice for Black empowerment, identity, and avant-garde aesthetics."
  },
  {
    "id": "aya-nakamura",
    "name": "Aya Nakamura",
    "country": "France",
    "continent": "Europe",
    "genre": "Afropop, R&B, Zouk,R&B,Pop",
    "city": "Bamako",
    "state": "Bamako District",
    "becameFamousIn": "2018",
    "becameFamousPlace": "Paris, France",
    "birthDate": "May 10, 1995",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/en/4/48/Aya_Nakamura_-_Aya.png?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
    "gifUrl": null,
    "impact": "Became the most-streamed Francophone female artist worldwide, modernizing French pop by fusing Parisian slang, Afrobeats, and Caribbean zouk rhythms to global mainstream audiences."
  },
  {
    "id": "anri",
    "name": "Anri",
    "country": "Japan",
    "continent": "Asia",
    "genre": "City Pop, J-Pop, R&B, Jazz",
    "city": "Yamato",
    "state": "Kanagawa",
    "becameFamousIn": "1978",
    "becameFamousPlace": "Tokyo, Japan",
    "birthDate": "August 31, 1961",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://secondhandsongs.com/picture/216974",
    "gifUrl": null,
    "impact": "Pioneered the 1980s Japanese City Pop movement, blending West Coast pop, disco, and funk, which experienced a massive modern global resurgence and heavily influenced internet microgenres like Future Funk and Vaporwave."
  },
  {
    "id": "hozier",
    "name": "Hozier",
    "country": "Ireland",
    "continent": "Europe",
    "genre": "Indie Rock, Soul, Folk, Blues,R&B",
    "city": "Bray",
    "state": "County Wicklow",
    "becameFamousIn": "2013",
    "becameFamousPlace": "Dublin, Ireland",
    "birthDate": "March 17, 1990",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://static.wixstatic.com/media/eaaed4_e90d6072dd304195b92cdaa2e1ce033a~mv2.webp/v1/fill/w_568,h_378,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/eaaed4_e90d6072dd304195b92cdaa2e1ce033a~mv2.webp",
    "gifUrl": null,
    "impact": "Bridged blues, gospel, and folk into modern pop culture while using his massive breakthrough platform with 'Take Me to Church' to advocate against institutional oppression, religious hypocrisy, and LGBTQ+ discrimination."
  },
  {
    "id": "celine-dion",
    "name": "Céline Dion",
    "country": "Canada",
    "continent": "North America",
    "genre": "Pop, Soft rock",
    "city": "Charlemagne",
    "state": "Quebec",
    "becameFamousIn": "1981",
    "becameFamousPlace": "Montreal, Quebec, Canada",
    "birthDate": "March 30, 1968",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgTkOiognlrzbaKwnlAQ6ShTaBMH7lja2ZzdbWXM_IkBYzRCrzhplWmxL_&s=10",
    "gifUrl": null,
    "impact": "One of the best-selling vocalists in music history, she elevated cinematic pop ballads to unprecedented global heights, popularized modern Las Vegas artist residencies, and broke monumental language barriers across French and English markets."
  },
  {
    "id": "tems",
    "name": "Tems",
    "country": "Nigeria",
    "continent": "Africa",
    "genre": "Afrobeats, Alté, R&B",
    "city": "Lagos",
    "state": "Lagos State",
    "becameFamousIn": "2020",
    "becameFamousPlace": "Lagos, Nigeria",
    "birthDate": "June 11, 1995",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://npr.brightspotcdn.com/dims3/default/strip/false/crop/3000x2489+0+0/resize/3000x2489!/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Fa3%2Fa7%2F81b890fc4f7b8ce7aafc80d8ec3f%2Ftems.jpg",
    "gifUrl": null,
    "impact": "A pivotal force in pushing contemporary African music and Alté culture into the global mainstream, earning international chart success, major awards, and high-profile global collaborations."
  },
  {
    "id": "dijon-duenas",
    "name": "Dijon Duenas",
    "country": "United States",
    "continent": "North America",
    "genre": "Alternative R&B, Neo-soul,Americana",
    "city": "Ellicott City",
    "state": "Maryland",
    "becameFamousIn": "2018",
    "becameFamousPlace": "Los Angeles, California, United States",
    "birthDate": "October 2, 1993",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://media.i-d.co/wp-content/uploads/2024/05/1553011672210-Dijon-2-copy-2.jpeg",
    "gifUrl": null,
    "impact": "Pioneered a raw, highly intimate, live-recorded aesthetic within contemporary indie pop and alternative R&B, expanding production boundaries for modern DIY singer-songwriters."
  },
  {
    "id": "sade",
    "name": "Sade",
    "country": "United Kingdom",
    "continent": "Europe",
    "genre": "Smooth Soul, Sophisti-Pop, Quiet Storm",
    "city": "Ibadan",
    "state": "Oyo State",
    "becameFamousIn": "1984",
    "becameFamousPlace": "London, United Kingdom",
    "birthDate": "January 16, 1959",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://i.guim.co.uk/img/media/3de12feb5fe12aa19cd715fdbd3b0bf5f7d66654/0_0_4683_3748/master/4683.jpg?width=465&dpr=1&s=none&crop=none",
    "gifUrl": null,
    "impact": "Architect of the modern smooth soul and sophisti-pop sound; her timeless minimalist arrangements, distinctive tone, and quiet artistic mystery profoundly shaped alternative R&B, neo-soul, and hip-hop sampling for decades."
  },
  {
    "id": "dolly-parton",
    "name": "Dolly Parton",
    "country": "United States",
    "continent": "North America",
    "genre": "Country, Bluegrass, Pop, gospel",
    "city": "Pittman Center",
    "state": "Tennessee",
    "becameFamousIn": "1967",
    "becameFamousPlace": "Nashville, Tennessee, United States",
    "birthDate": "January 19, 1946",
    "deathDate": "August 25, 2026",
    "deathReason": "official cause of death was cancer, following what her representatives described as a brief battle with the disease",
    "imageUrl": "https://i0.wp.com/nashvillebanner.com/wp-content/uploads/2026/08/AP284714668927-scaled.jpg?fit=780%2C519&ssl=1",
    "gifUrl": "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExb25rYmVkMWlkMGVlZzQ2MXd6eDh2azZ3dDlwdTBjeXRxZnBuZWtuciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/XfscsiXH3NnZG8yL9A/giphy.gif",
    "impact": "A trailblazing songwriter, business mogul, and cultural icon who revolutionized female autonomy in country music, authored fundamental American standards, and driven massive global philanthropy including her Imagination Library."
  },
  {
    "id": "bonnie-tyler",
    "name": "Bonnie Tyler",
    "country": "United Kingdom",
    "continent": "Europe",
    "genre": "Pop Rock, Soft Rock",
    "city": "Skewen",
    "state": "Neath Port Talbot",
    "becameFamousIn": "1977",
    "becameFamousPlace": "London, United Kingdom",
    "birthDate": "June 8, 1951",
    "deathDate": "July 8, 2026",
    "deathReason": " has died at age 75 after undergoing emergency intestinal surgery and being put in a medically induced coma earlier this year.",
    "imageUrl": "https://i.guim.co.uk/img/media/a45f2b1713daff4c595d6dd86ed683b18749f727/0_0_2581_3878/master/2581.jpg?width=375&dpr=1&s=none&crop=none",
    "gifUrl": "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExdHg4YXRxMDVhZmdiZmhjbnJ3a3ZxbnBjZnE0MzUzcjhiZGkyaWU5ZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/mI8V8j8jqyppWWHqPc/giphy.gif",
    "impact": "Distinguished by her iconic rasping vocal timber, she delivered timeless, theatrical stadium pop-rock anthems like 'Total Eclipse of the Heart' and 'Holding Out for a Hero' that defined 1980s pop production."
  },
  {
    "id": "giveon",
    "name": "Giveon",
    "country": "United States",
    "continent": "North America",
    "genre": "R&B, Soul",
    "city": "Long Beach",
    "state": "California",
    "becameFamousIn": "2020",
    "becameFamousPlace": "Los Angeles, California, United States",
    "birthDate": "February 21, 1995",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/61a66ed8d16de5d8c003d8ca/0x0.jpg?format=jpg&height=1200&width=400&fit=bounds",
    "gifUrl": null,
    "impact": "Helped reinvigorate classic, rich baritone vocal styles in mainstream contemporary R&B, leading a wave of modern soul balladry across international charts."
  },
  {
    "id": "snoop-dogg",
    "name": "Snoop Dogg",
    "country": "United States",
    "continent": "North America",
    "genre": "West Coast Hip Hop, G-Funk",
    "city": "Long Beach",
    "state": "California",
    "becameFamousIn": "1992",
    "becameFamousPlace": "Los Angeles, California, United States",
    "birthDate": "October 20, 1971",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://i.pinimg.com/474x/0d/50/61/0d506172a75540be30dab1ec0be8c3a2.jpg",
    "gifUrl": null,
    "impact": "Pioneered the relaxed, melodic flow of West Coast G-Funk on historic releases like 'Doggystyle', seamlessly evolving over three decades into a ubiquitous global pop-culture figure, entrepreneur, and media icon."
  },
  {
    "id": "dr-dre",
    "name": "Dr. Dre",
    "country": "United States",
    "continent": "North America",
    "genre": "West Coast Hip Hop, Gangsta Rap, G-Funk",
    "city": "Compton",
    "state": "California",
    "becameFamousIn": "1988",
    "becameFamousPlace": "Los Angeles, California, United States",
    "birthDate": "February 18, 1965",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://djmag.com/sites/default/files/styles/djm_23_1005x565/public/2024-03/dj-mag-news-dr-dre.jpg.webp?itok=pJFoyswE684362470",
    "gifUrl": null,
    "impact": "Masterminded the sonic evolution of West Coast hip-hop through N.W.A, G-Funk, and Aftermath; nurtured monumental careers like Snoop Dogg, Eminem, and 50 Cent, and reshaped tech entrepreneurship via Beats Electronics."
  },
  {
    "id": "diddy",
    "name": "Sean Combs (Diddy)",
    "country": "United States",
    "continent": "North America",
    "genre": "East Coast Hip Hop, Pop Rap, R&B",
    "city": "New York City",
    "state": "New York",
    "becameFamousIn": "1993",
    "becameFamousPlace": "New York City, New York, United States",
    "birthDate": "November 4, 1969",
    "isIncarcerated": true,
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://images.paramount.tech/uri/mgid:arc:imageassetref:bet.com:2f07aca6-f7e8-11e8-a442-0e40cf2fc285?quality=0.7&gen=ntrn",
    "gifUrl": null,
    "impact": "Architected the commercial 'Shiny Suit' era of hip-hop via Bad Boy Records, building a monumental blueprint for hip-hop executive moguldom across music, fashion, and lifestyle branding."
  },
  {
    "id": "ciara",
    "name": "Ciara",
    "country": "United States",
    "continent": "North America",
    "genre": "R&B, Crunkcore, Pop, Dance",
    "city": "Austin",
    "state": "Texas",
    "becameFamousIn": "2004",
    "becameFamousPlace": "Atlanta, Georgia, United States",
    "birthDate": "October 25, 1985",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://www.hollywoodreporter.com/wp-content/uploads/2016/05/ciara.jpg",
    "gifUrl": null,
    "impact": "Dubbed the 'First Lady of Crunk&B', she popularized high-energy dance choreography integrated with southern uptempo R&B production, shaping mid-2000s pop dance culture."
  },
  {
    "id": "mariah-carey",
    "name": "Mariah Carey",
    "country": "United States",
    "continent": "North America",
    "genre": "R&B, Pop, Soul",
    "city": "Huntington",
    "state": "New York",
    "becameFamousIn": "1990",
    "becameFamousPlace": "New York City, New York, United States",
    "birthDate": "March 27, 1969",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://wror.com/uploads/2022/10/GettyImages-1427040305-scaled-e1666027780808.jpg",
    "gifUrl": null,
    "impact": "Famed for her five-octave vocal range and mastery of the whistle register; popularized melisma in modern pop, pioneered pop-R&B/hip-hop vocal remix collaborations, and crafted perennial global classics."
  },
  {
    "id": "common",
    "name": "Common",
    "country": "United States",
    "continent": "North America",
    "genre": "Conscious Hip Hop, Neo-Soul",
    "city": "Chicago",
    "state": "Illinois",
    "becameFamousIn": "1992",
    "becameFamousPlace": "Chicago, Illinois, United States",
    "birthDate": "March 13, 1972",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5f/Common.jpg/250px-Common.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    "gifUrl": null,
    "impact": "Pioneered conscious midwestern hip-hop and neo-soul synergy, providing poetic reflections on social justice, love, and spirituality while achieving EGOT-adjacent acclaimed cross-media recognition."
  },
  {
    "id": "kurupt",
    "name": "Kurupt",
    "country": "United States",
    "continent": "North America",
    "genre": "West Coast Hip Hop, Gangsta Rap, G-Funk",
    "city": "Philadelphia",
    "state": "Pennsylvania",
    "becameFamousIn": "1992",
    "becameFamousPlace": "Los Angeles, California, United States",
    "birthDate": "November 23, 1972",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://dailynexus.s3-us-west-1.amazonaws.com/dailynexus/wp-content/uploads/2016/01/Kurupt.jpg",
    "gifUrl": null,
    "impact": "One half of Tha Dogg Pound; widely respected for his dense, complex cadence and razor-sharp lyricism that raised the technical bar for West Coast gangsta rap during the Golden Era."
  },
  {
    "id": "daz-dillinger",
    "name": "Daz Dillinger",
    "country": "United States",
    "continent": "North America",
    "genre": "West Coast Hip Hop, Gangsta Rap, G-Funk",
    "city": "Long Beach",
    "state": "California",
    "becameFamousIn": "1992",
    "becameFamousPlace": "Los Angeles, California, United States",
    "birthDate": "May 25, 1973",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://townsquare.media/site/812/files/2016/05/Daz-Dillinger-2018.jpg?w=780&q=75",
    "gifUrl": null,
    "impact": "Essential producer and rapper behind Death Row Records' legendary catalog; co-architected key sonic blueprints for 2Pac's 'All Eyez on Me' and Tha Dogg Pound classics."
  },
  {
    "id": "warren-g",
    "name": "Warren G",
    "country": "United States",
    "continent": "North America",
    "genre": "West Coast Hip Hop, G-Funk",
    "city": "Long Beach",
    "state": "California",
    "becameFamousIn": "1994",
    "becameFamousPlace": "Los Angeles, California, United States",
    "birthDate": "November 10, 1970",
    "deathDate": null,
    "deathReason": null,
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUATdLDr3uk9MRV55gbxumwun-49MfDCa4rsxdOeBLvQ&s",
    "gifUrl": null,
    "impact": "Helped bring G-Funk to the pop mainstream with the evergreen classic 'Regulate', demonstrating a smoother, melodic alternative within 1990s West Coast hip-hop."
  },
  {
    "id": "miki-matsubara",
    "name": "Miki Matsubara",
    "country": "Japan",
    "continent": "Asia",
    "genre": "City Pop, Jazz Pop, Funk",
    "city": "Kishiwada",
    "state": "Osaka",
    "becameFamousIn": "1979",
    "becameFamousPlace": "Tokyo, Japan",
    "birthDate": "November 28, 1959",
    "deathDate": "October 7, 2004",
    "deathReason": "Complications from cervical cancer",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/en/c/c0/Mikimatsubaraphoto.jpg?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
    "gifUrl": "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExYjJubGIxeG11dnVvYndoYTl6azU1amFzNnkyajNtNXJxMmJ5dmpybyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/bGkOcTT6NjuRQQEAAj/giphy.gif",
    "impact": "Recorded the timeless iconic track 'Mayonaka no Door / Stay With Me', serving as a central foundational pillar for Japan's 1980s City Pop movement and driving its viral global internet revival decades later."
  },
  {
    "id": "bobby-day",
    "name": "Bobby Day",
    "country": "United States",
    "continent": "North America",
    "genre": "Rock and Roll, R&B, Doo-Wop",
    "city": "Fort Worth",
    "state": "Texas",
    "becameFamousIn": "1958",
    "becameFamousPlace": "Los Angeles, California, United States",
    "birthDate": "July 1, 1928",
    "deathDate": "July 27, 1990",
    "deathReason": "Prostate cancer",
    "imageUrl": "https://i.scdn.co/image/ab6761610000e5ebdb051dbf9e2253e365fdea81",
    "gifUrl": "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExYjJubGIxeG11dnVvYndoYTl6azU1amFzNnkyajNtNXJxMmJ5dmpybyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/bGkOcTT6NjuRQQEAAj/giphy.gif",
    "impact": "Helped define early American rock and roll and R&B as both a hit performer and songwriter, crafting timeless classics like 'Rockin' Robin' and 'Little Bitty Pretty One' that became fundamental standards covered across generations."
  },
  {
    "id": "amy-winehouse",
    "name": "Amy Winehouse",
    "country": "United Kingdom",
    "continent": "Europe",
    "genre": "Soul, Blue-Eyed Soul, Jazz, R&B",
    "city": "London",
    "state": "Greater London",
    "becameFamousIn": "2003",
    "becameFamousPlace": "London, United Kingdom",
    "birthDate": "September 14, 1983",
    "deathDate": "July 23, 2011",
    "deathReason": "Accidental alcohol poisoning",
    "imageUrl": "https://www.rockarchive.com/media/1016/amy-winehouse-amyw001mmaw.jpg?crop=0,0.046048722519310754,0,0.28550207961972673&cropmode=percentage&width=800&height=800&rnd=133548210960000000&overlay=watermark.png&overlay.size=230,20&overlay.position=0,780",
    "gifUrl": "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExbW5yMzh3dTA3cW5paTZ2YXFzM3BxODh6b2J4dnM0cnc5OGxrZ2hnYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/tB7gCNjgmaAxy/giphy.gif",
    "impact": "Spearheaded the 2000s retro-soul resurgence and opened international doors for a generation of British female vocalists, while offering raw, unvarnished lyricism on addiction, mental health, and heartbreak."
  },
  {
    "id": "selena-quintanilla",
    "name": "Selena Quintanilla",
    "country": "United States",
    "continent": "North America",
    "genre": "Tejano, Cumbia, Latin Pop",
    "city": "Lake Jackson",
    "state": "Texas",
    "becameFamousIn": "1989",
    "becameFamousPlace": "Corpus Christi, Texas, United States",
    "birthDate": "April 16, 1971",
    "deathDate": "March 31, 1995",
    "deathReason": "Homicide (shot by Yolanda Saldívar)",
    "imageUrl": "https://www.elpasotimes.com/gcdn/-mm-/cfbdb7faeb97f5562b04d42a29db7e62f5a5badc/c=0-143-1354-1948/local/-/media/2017/11/01/TXNMGroup/ElPaso/636451437932185421-PNITab-05-05-2017-Z8-1-A002-2017-05-03-IMG-Selena-Quintanilla-1-1-T4I93ILQ-L1022479931-IMG-Selena-Quintanilla-1-1-T4I93ILQ.jpg?width=458&height=610&fit=crop&format=pjpg&auto=webp",
    "gifUrl": "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmJwajdiY295ZzQ3aW9mNjY4Z3E1aTBrZWwydTc3a2UxOWJsdjlrbSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3oKIPsatBJq8BQb5DO/giphy.gif",
    "impact": "Reigned as the 'Queen of Tejano Music', breaking down massive barriers in a male-dominated genre, pioneering cross-cultural fashion and music, and serving as a timeless cultural beacon for Latinx representation worldwide."
  },
  {
    "id": "chester-bennington",
    "name": "Chester Bennington",
    "country": "United States",
    "continent": "North America",
    "genre": "Nu Metal, Alternative Rock, Hard Rock",
    "city": "Phoenix",
    "state": "Arizona",
    "becameFamousIn": "2000",
    "becameFamousPlace": "Los Angeles, California, United States",
    "birthDate": "March 20, 1976",
    "deathDate": "July 20, 2017",
    "deathReason": "Suicide by hanging",
    "imageUrl": "https://www.shutterstock.com/editorial/image-editorial/N9T8Ae44McT8I135NTkz/chester-bennington-440nw-506889g.jpg",
    "gifUrl": "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExbmltbzZqcDJjeDdvaGFoc2E2dW91OGZkeGszbnRrY29tdWoxcTR0dSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Bn4XQMzfZPMd2/giphy.gif",
    "impact": "Defined the vocal sound of turn-of-the-millennium rock with Linkin Park, blending cathartic scream technique with emotional vulnerability that validated mental health struggles for an entire generation."
  },
  {
    "id": "eazy-e",
    "name": "Eazy-E",
    "country": "United States",
    "continent": "North America",
    "genre": "Gangsta Rap, West Coast Hip Hop",
    "city": "Compton",
    "state": "California",
    "becameFamousIn": "1987",
    "becameFamousPlace": "Los Angeles, California, United States",
    "birthDate": "September 7, 1964",
    "deathDate": "March 26, 1995",
    "deathReason": "Complications from AIDS",
    "imageUrl": "https://www.vibe.com/wp-content/uploads/2015/08/eazy-e-vibe-cover-1.jpg?w=1024",
    "gifUrl": "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExbDY4Y3Vtb2hxMHQ2OTJ4eTRzeHp2NzBpNGdrMXJtd2ZlNHN0Y3BtYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/UDVTRm69LC3sc/giphy.gif",
    "impact": "Hailed as the 'Godfather of Gangsta Rap', he co-founded N.W.A and Ruthless Records, establishing the template for independent West Coast hip-hop business models and explicit urban reality storytelling."
  },
  {
    "id": "big-l",
    "name": "Big L",
    "country": "United States",
    "continent": "North America",
    "genre": "East Coast Hip Hop, Hardcore Rap, Horrorcore",
    "city": "New York City",
    "state": "New York",
    "becameFamousIn": "1995",
    "becameFamousPlace": "New York City, New York, United States",
    "birthDate": "May 30, 1974",
    "deathDate": "February 15, 1999",
    "deathReason": "Homicide (drive-by shooting)",
    "imageUrl": "https://i.pinimg.com/236x/f4/20/0b/f4200b811668b630e42e34677c0c3837.jpg",
    "gifUrl": "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExMmZvMHptN2dsczcwaWwycTBlem9mbzFlNmR6NXRld3BvaHo5cWlpNyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/IywHisvtcf2Y8/giphy.gif",
    "impact": "Celebrated as one of hip-hop's most technically gifted lyricists, setting gold standards for multisyllabic rhyme schemes, punchlines, and underground East Coast street poetry before his tragic death."
  },
  {
    "id": "biggie",
    "name": "The Notorious B.I.G.",
    "country": "United States",
    "continent": "North America",
    "genre": "East Coast Hip Hop, Gangsta Rap",
    "city": "New York City",
    "state": "New York",
    "becameFamousIn": "1994",
    "becameFamousPlace": "New York City, New York, United States",
    "birthDate": "May 21, 1972",
    "deathDate": "March 9, 1997",
    "deathReason": "Homicide (drive-by shooting)",
    "imageUrl": "https://www.indiewire.com/wp-content/uploads/2016/07/notorious-big.jpg",
    "gifUrl": "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ25sZG5tM3YwaWRtcG1mcXY0c3pyM2g4cnY5MHMxNXphYmQzN3dobiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/lfxVZngS8TG3m/giphy.gif",
    "impact": "Widely regarded as one of the greatest rappers of all time; revitalized East Coast hip-hop with unmatched narrative lyricism, effortless rhythmic flow, and timeless radio hitmaking."
  },
  {
    "id": "nate-dogg",
    "name": "Nate Dogg",
    "country": "United States",
    "continent": "North America",
    "genre": "West Coast Hip Hop, G-Funk, R&B",
    "city": "Clarksdale",
    "state": "Mississippi",
    "becameFamousIn": "1992",
    "becameFamousPlace": "Long Beach, California, United States",
    "birthDate": "August 19, 1969",
    "deathDate": "March 15, 2011",
    "deathReason": "Complications from multiple strokes",
    "imageUrl": "https://www.nme.com/wp-content/uploads/2016/09/NateDoggPA160311-2.jpg",
    "gifUrl": "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExZmc4ajFsanQ3NXhucjE2Mmo5dWt1N2p0bnVhZ2J1Mm1nMWwwZmlqYiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/EF4ZndL9dkJck/giphy.gif",
    "impact": "The definitive hook master of West Coast hip-hop, whose deep soulful baritone melodies transformed dozens of iconic rap singles into massive global hits throughout the 1990s and 2000s."
  }
];
export default artists;